name: "Reusable Deployment"

on:
  workflow_call:
    inputs:
      MONGO_URI:
        required: true
        type: string
      environment:
        required: true
        type: string
      k8s-manifest-dir:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_CREDENTIALS:
        required: true
      MONGO_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      APP_INGRESS_URL: ${{ steps.get-url.outputs.ingress }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set kubectl context
        run: |
          az aks get-credentials \
            --resource-group MyResourceGroup \
            --name MyAKSCluster \
            --overwrite-existing

      - name: Deploy manifests
        run: |
          echo "Deploying to ${{ inputs.environment }}"
          kubectl apply -f ${{ inputs.k8s-manifest-dir }}

      - name: Get Ingress URL
        id: get-url
        run: |
          URL=$(kubectl get ingress solar-system -o jsonpath='{.spec.rules[0].host}')
          echo "ingress=$URL" >> $GITHUB_OUTPUT
